#!/bin/bash

set -e
set -u
set -o pipefail

mkdir -p /opt/snap/bin
mkdir -p /opt/snap/plugins
mkdir -p /var/log/snap
mkdir -p /etc/snap

curl -sfL "https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/snap/master/${SNAP_VERSION}/snapd" -o /opt/snap/bin/snapd
curl -sfL "https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/snap/master/${SNAP_VERSION}/snapctl" -o /opt/snap/bin/snapctl
chmod 775 /opt/snap/bin/snapd
chmod 775 /opt/snap/bin/snapctl
ln -s /opt/snap/bin/snapd /usr/local/bin/snapd
ln -s /opt/snap/bin/snapctl /usr/local/bin/snapctl
